### ISSUE TITLE
doesn't work with 3.1 alpha

### ISSUE THREAD

**Issue by ViktorEvil** [IndicaInkwell/godot-ios-deploy#1]
plugin will not activate when using Godot 3.1 alpha

it complains that its not a tool and will not let me change its status to active.

Apple icon is a little blurry on 3.0.6 as well but it might be because I'm still using a MacBook Air and don't have a retina screen?

love this add-on though, it has saved me hours of build time and should be part of Godot as standard

**Comment by PrestonKnopp** [comment]
My bad, accidentally closed this.

Hey, thanks for posting an issue. Yeah, it doesn't work for 3.1 because of gdscript's stricter typing. I'm going to have to refactor a bit to use exact godot api (Array vs PoolStringArray).

I'm not sure about the icon i'll have to check that out.

Awesome! I'm glad it saves you some time :)

**Comment by PrestonKnopp** [comment]
This is actually a bigger refactor than I thought. I'm going to create a 3.1 branch and merge it once godot 3.1 is stable.

**Comment by PrestonKnopp** [comment]
Hey, @ViktorEvil, I just realized you're from the reddit thread. Sorry about the long wait.

I just wrapped up some testing on the 3.1 branch and it's working. If you could test that out I'd appreciate it.

**Comment by ViktorEvil** [comment]
No problem, appreciate you taking the time for getting this running on 3.1.

I try a build of my project every week or so on the latest 3.1 build just to pre-empt any compatibility problems later. This 3.1 fork works great so I guess you can close this issue.
